/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Jun 19 2015
 * Processor: PIC16F877
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }